include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    prefer_single_quotes: true
    always_use_package_imports: true
    flutter_style_todos: false
    avoid_redundant_argument_values: false
    sort_pub_dependencies: false
# analyzer:
#   errors:
#     missing_return: error
#     must_be_immutable: error
#     must_call_super: error
#     invalid_use_of_protected_member: error
#     parameter_assignments: error
#     sort_unnamed_constructors_first: ignore
#     sort_pub_dependencies: ignore
#   exclude:
#     - "**/*.g.dart"
#     - "**/*.freezed.dart"

# linter:
#   rules:
#     avoid_print: false
#     prefer_single_quotes: true
#     always_use_package_imports: true
#     flutter_style_todos: false
#     avoid_redundant_argument_values: false
#     sort_pub_dependencies: false